server:
  port: 5555

spring:
  application:
    name: revfit-api
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default-schema: ${DB_SCHEMA}
    show-sql: false